export const T = {
  TYPE: "TYPE",
  USER_LOGIN: "USER_LOGIN",
  USER_LOG_OUT: "USER_LOG_OUT",
  CHAT_ADD_DATA: "CHAT_ADD_DATA",
  REGISTER_USER: "REGISTER_USER",
  GET_USER_DATA: "GET_USER_DATA",
  UPSERT_USER_INTO_FIRESTORE: "UPSERT_USER_INTO_FIRESTORE",
};
