export const T = {
  TYPE: "TYPE",
  USER_LOGIN: "USER_LOGIN",
  USER_LOG_OUT: "USER_LOG_OUT",
  CHAT_ADD_DATA: "CHAT_ADD_DATA",
  REGISTER_USER: "REGISTER_USER",
  SET_USER_DATA_ON_SOTRE: "SET_USER_DATA_ON_SOTRE",
  GET_USER_DATA: "GET_USER_DATA",
  UPSERT_USER_INTO_FIRESTORE: "UPSERT_USER_INTO_FIRESTORE",
  UPDATE_HEIGHT: "UPDATE_HEIGHT",
  UPDATE_LOCATION: "UPDATE_LOCATION",
  UPDATE_HOBBIES: "UPDATE_HOBBIES",
  UPDATE_PERSONALITY: "UPDATE_PERSONALITY",
  UPDATE_SMOKING: "UPDATE_SMOKING",
  UPDATE_DRINKING: "UPDATE_DRINKING",
  ADD_VOTE_HISTORY: "ADD_VOTE_HISTORY"
};
